name: fmcg_sales
version: 1.0.0
config-version: 2

profile: fmcg_sales

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  fmcg_sales:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
